# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171211_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
        ),
    ]
